use std::env;
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;
use zstd::stream::encode_all;

const EMBED_MANIFEST: &str = ".sagens-state/embed-manifest.json";

#[derive(Debug, Deserialize)]
struct EmbedManifest {
    kernel: PathBuf,
    rootfs: PathBuf,
    firmware: Option<PathBuf>,
}

#[derive(Clone, Copy)]
enum CompressionMode {
    None,
    Zstd,
}

#[cfg(unix)]
fn asset_mode(path: &Path) -> u32 {
    use std::os::unix::fs::PermissionsExt;

    fs::metadata(path)
        .expect("read embedded asset metadata")
        .permissions()
        .mode()
}

#[cfg(not(unix))]
fn asset_mode(_: &Path) -> u32 {
    0o644
}

fn main() {
    emit_macos_weak_hypervisor_link_args();

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = resolve_workspace_root(&manifest_dir);
    let manifest_path = workspace_root.join(EMBED_MANIFEST);
    println!(
        "cargo:rustc-env=SAGENS_WORKSPACE_ROOT={}",
        workspace_root.display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Cargo.toml").display()
    );
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-env-changed=SAGENS_GITHUB_REPO");
    println!("cargo:rerun-if-env-changed=SAGENS_REPO");
    if let Some(repo) = discover_release_repo(&workspace_root) {
        println!("cargo:rustc-env=SAGENS_RELEASE_REPO={repo}");
    }
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("embedded_bundle.rs");
    fs::write(&generated, render_assets(&manifest_path, &workspace_root))
        .expect("write embedded bundle");
}

fn emit_macos_weak_hypervisor_link_args() {
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    if target_os != "macos" || target_arch != "aarch64" {
        return;
    }

    for symbol in [
        "hv_vm_config_get_el2_supported",
        "hv_vm_config_set_el2_enabled",
        "hv_gic_config_create",
        "hv_gic_config_set_distributor_base",
        "hv_gic_config_set_redistributor_base",
        "hv_gic_create",
        "hv_gic_get_distributor_size",
        "hv_gic_get_redistributor_size",
        "hv_gic_set_spi",
    ] {
        println!("cargo:rustc-link-arg-bins=-Wl,-U,_{symbol}");
        println!("cargo:rustc-link-arg-tests=-Wl,-U,_{symbol}");
    }
}

fn render_assets(manifest_path: &Path, workspace_root: &Path) -> String {
    let mut body = String::from("// @generated by build.rs\n");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let Some(manifest) = load_manifest(manifest_path, workspace_root) else {
        body.push_str("pub static KERNEL: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static ROOTFS: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static FIRMWARE: Option<EmbeddedAsset> = None;\n");
        return body;
    };

    body.push_str(&render_required_asset("KERNEL", &manifest.kernel, &out_dir));
    body.push_str(&render_required_asset("ROOTFS", &manifest.rootfs, &out_dir));
    body.push_str(&render_optional_asset(
        "FIRMWARE",
        manifest.firmware.as_deref(),
        &out_dir,
    ));
    body
}

fn load_manifest(manifest_path: &Path, repo_root: &Path) -> Option<EmbedManifest> {
    read_manifest(manifest_path).or_else(|| discover_default_manifest(repo_root))
}

fn read_manifest(path: &Path) -> Option<EmbedManifest> {
    let bytes = fs::read(path).ok()?;
    serde_json::from_slice(&bytes).ok()
}

fn discover_default_manifest(repo_root: &Path) -> Option<EmbedManifest> {
    let target_os = env::var("CARGO_CFG_TARGET_OS").ok()?;
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").ok()?;
    let platform = match (target_os.as_str(), target_arch.as_str()) {
        ("macos", "aarch64") => ("macos-aarch64", "alpine-aarch64"),
        ("macos", "x86_64") => ("macos-x86_64", "alpine-x86_64"),
        ("linux", "aarch64") => ("linux-aarch64", "alpine-aarch64"),
        ("linux", "x86_64") => ("linux-x86_64", "alpine-x86_64"),
        _ => return None,
    };
    let guest_dir = repo_root.join("artifacts").join(platform.1);
    let kernel = default_kernel_candidate(&guest_dir, target_os.as_str(), target_arch.as_str());
    let rootfs = guest_dir.join("rootfs.raw");
    let firmware = match target_os.as_str() {
        "macos" => Some(
            repo_root
                .join("third_party")
                .join("upstream")
                .join("libkrun")
                .join("edk2")
                .join("KRUN_EFI.silent.fd"),
        ),
        "linux" => None,
        _ => return None,
    };

    for candidate in [&kernel, &rootfs] {
        println!("cargo:rerun-if-changed={}", candidate.display());
    }
    if let Some(path) = &firmware {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    if !kernel.is_file() || !rootfs.is_file() {
        return None;
    }
    if let Some(path) = &firmware
        && !path.is_file()
    {
        return None;
    }

    Some(EmbedManifest {
        kernel,
        rootfs,
        firmware,
    })
}

fn default_kernel_candidate(guest_dir: &Path, target_os: &str, target_arch: &str) -> PathBuf {
    if target_os == "linux" && target_arch == "x86_64" {
        let compressed = guest_dir.join("vmlinuz-virt.pe.gz");
        if compressed.is_file() {
            return compressed;
        }
    }
    guest_dir.join("vmlinuz-virt")
}

fn render_required_asset(name: &str, path: &Path, out_dir: &Path) -> String {
    println!("cargo:rerun-if-changed={}", path.display());
    format!(
        "pub static {name}: Option<EmbeddedAsset> = Some({asset});\n",
        asset = render_embedded_asset(path, out_dir),
    )
}

fn render_optional_asset(name: &str, path: Option<&Path>, out_dir: &Path) -> String {
    match path {
        Some(path) => render_required_asset(name, path, out_dir),
        None => format!("pub static {name}: Option<EmbeddedAsset> = None;\n"),
    }
}

fn render_embedded_asset(path: &Path, out_dir: &Path) -> String {
    let (asset_path, compression) = write_embedded_asset(path, out_dir);
    format!(
        "EmbeddedAsset {{ file_name: {file_name:?}, bytes: include_bytes!(r#\"{asset_path}\"#), compression: Compression::{compression}, mode: {mode}, }}",
        file_name = file_name(path),
        asset_path = asset_path.display(),
        compression = compression.variant_name(),
        mode = asset_mode(path),
    )
}

fn write_embedded_asset(path: &Path, out_dir: &Path) -> (PathBuf, CompressionMode) {
    let asset_dir = out_dir.join("embedded-assets");
    fs::create_dir_all(&asset_dir).expect("create embedded asset dir");
    let source = fs::read(path).expect("read embedded asset");
    let compressed = encode_all(Cursor::new(&source), 3).expect("compress embedded asset");
    if compressed.len() >= source.len() {
        return (path.to_path_buf(), CompressionMode::None);
    }
    let output_name = compressed_file_name(path);
    let output_path = asset_dir.join(output_name);
    fs::write(&output_path, compressed).expect("write compressed embedded asset");
    (output_path, CompressionMode::Zstd)
}

fn compressed_file_name(path: &Path) -> String {
    let original = file_name(path);
    format!("{original}.zst")
}

impl CompressionMode {
    fn variant_name(self) -> &'static str {
        match self {
            Self::None => "None",
            Self::Zstd => "Zstd",
        }
    }
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("artifact.bin")
        .to_string()
}

fn resolve_workspace_root(manifest_dir: &Path) -> PathBuf {
    for candidate in manifest_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(contents) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if contents.contains("[workspace]") {
            return candidate.to_path_buf();
        }
    }
    manifest_dir.to_path_buf()
}

fn discover_release_repo(workspace_root: &Path) -> Option<String> {
    env::var("SAGENS_GITHUB_REPO")
        .ok()
        .filter(|value| !value.trim().is_empty())
        .or_else(|| {
            env::var("SAGENS_REPO")
                .ok()
                .filter(|value| !value.trim().is_empty())
        })
        .or_else(|| git_origin_repo(workspace_root))
        .or_else(|| {
            env::var("CARGO_PKG_REPOSITORY")
                .ok()
                .and_then(|value| parse_github_repo(&value))
        })
}

fn git_origin_repo(workspace_root: &Path) -> Option<String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(workspace_root)
        .args(["remote", "get-url", "origin"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let url = String::from_utf8(output.stdout).ok()?;
    parse_github_repo(url.trim())
}

fn parse_github_repo(value: &str) -> Option<String> {
    let slug = value
        .strip_prefix("git@github.com:")
        .or_else(|| value.strip_prefix("ssh://git@github.com/"))
        .or_else(|| value.strip_prefix("https://github.com/"))
        .or_else(|| value.strip_prefix("http://github.com/"))?
        .trim()
        .trim_matches('/')
        .trim_end_matches(".git");

    let mut parts = slug.split('/');
    let owner = parts.next()?.trim();
    let repo = parts.next()?.trim();
    if owner.is_empty() || repo.is_empty() || parts.next().is_some() {
        return None;
    }
    Some(format!("{owner}/{repo}"))
}
