use std::env;
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use zstd::stream::encode_all;

const EMBED_MANIFEST: &str = ".sagens-state/embed-manifest.json";

#[derive(Debug, Deserialize)]
struct EmbedManifest {
    libkrun: Option<PathBuf>,
    kernel: PathBuf,
    rootfs: PathBuf,
    firmware: Option<PathBuf>,
    #[serde(default)]
    runtime_support: Vec<PathBuf>,
}

#[derive(Clone, Copy)]
enum CompressionMode {
    None,
    Zstd,
}

#[cfg(unix)]
fn asset_mode(path: &Path) -> u32 {
    use std::os::unix::fs::PermissionsExt;

    fs::metadata(path)
        .expect("read embedded asset metadata")
        .permissions()
        .mode()
}

#[cfg(not(unix))]
fn asset_mode(_: &Path) -> u32 {
    0o644
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = resolve_workspace_root(&manifest_dir);
    let manifest_path = workspace_root.join(EMBED_MANIFEST);
    println!(
        "cargo:rustc-env=SAGENS_WORKSPACE_ROOT={}",
        workspace_root.display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("Cargo.toml").display()
    );
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("embedded_bundle.rs");
    fs::write(&generated, render_assets(&manifest_path, &workspace_root))
        .expect("write embedded bundle");
}

fn render_assets(manifest_path: &Path, workspace_root: &Path) -> String {
    let mut body = String::from("// @generated by build.rs\n");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let Some(manifest) = load_manifest(manifest_path, workspace_root) else {
        body.push_str("pub static LIBKRUN: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static KERNEL: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static ROOTFS: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static FIRMWARE: Option<EmbeddedAsset> = None;\n");
        body.push_str("pub static RUNTIME_SUPPORT: &[EmbeddedAsset] = &[];\n");
        return body;
    };

    body.push_str(&render_optional_asset(
        "LIBKRUN",
        manifest.libkrun.as_deref(),
        &out_dir,
    ));
    body.push_str(&render_required_asset("KERNEL", &manifest.kernel, &out_dir));
    body.push_str(&render_required_asset("ROOTFS", &manifest.rootfs, &out_dir));
    body.push_str(&render_optional_asset(
        "FIRMWARE",
        manifest.firmware.as_deref(),
        &out_dir,
    ));
    body.push_str("pub static RUNTIME_SUPPORT: &[EmbeddedAsset] = &[\n");
    for path in &manifest.runtime_support {
        println!("cargo:rerun-if-changed={}", path.display());
        body.push_str(&render_asset_entry(path, &out_dir));
    }
    body.push_str("];\n");
    body
}

fn load_manifest(manifest_path: &Path, repo_root: &Path) -> Option<EmbedManifest> {
    read_manifest(manifest_path).or_else(|| discover_default_manifest(repo_root))
}

fn read_manifest(path: &Path) -> Option<EmbedManifest> {
    let bytes = fs::read(path).ok()?;
    serde_json::from_slice(&bytes).ok()
}

fn discover_default_manifest(repo_root: &Path) -> Option<EmbedManifest> {
    let target_os = env::var("CARGO_CFG_TARGET_OS").ok()?;
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").ok()?;
    let platform = match (target_os.as_str(), target_arch.as_str()) {
        ("macos", "aarch64") => ("macos-aarch64", "alpine-aarch64", "libkrun.dylib"),
        ("macos", "x86_64") => ("macos-x86_64", "alpine-x86_64", "libkrun.dylib"),
        ("linux", "aarch64") => ("linux-aarch64", "alpine-aarch64", "libkrun.so"),
        ("linux", "x86_64") => ("linux-x86_64", "alpine-x86_64", "libkrun.so"),
        _ => return None,
    };
    let runtime_dir = repo_root
        .join("third_party")
        .join("runtime")
        .join(platform.0);
    let lib_dir = runtime_dir.join("lib");
    let libkrun = lib_dir.join(platform.2);
    let guest_dir = repo_root.join("artifacts").join(platform.1);
    let linux_x86_64_embedded_kernel = runtime_dir
        .join("share")
        .join("krunkit")
        .join("libkrunfw-kernel.elf");
    let kernel = match (target_os.as_str(), target_arch.as_str()) {
        ("linux", "x86_64") if linux_x86_64_embedded_kernel.is_file() => {
            linux_x86_64_embedded_kernel
        }
        ("macos", _) => guest_dir.join("vmlinuz-virt.pe.gz"),
        ("linux", _) => guest_dir.join("vmlinuz-virt"),
        _ => return None,
    };
    let rootfs = guest_dir.join("rootfs.raw");
    let firmware = match target_os.as_str() {
        "macos" => Some(
            runtime_dir
                .join("share")
                .join("krunkit")
                .join("KRUN_EFI.silent.fd"),
        ),
        "linux" => None,
        _ => return None,
    };

    for candidate in [&libkrun, &kernel, &rootfs] {
        println!("cargo:rerun-if-changed={}", candidate.display());
    }
    if let Some(path) = &firmware {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed={}", lib_dir.display());

    if !libkrun.is_file() || !kernel.is_file() || !rootfs.is_file() {
        return None;
    }
    if let Some(path) = &firmware
        && !path.is_file()
    {
        return None;
    }

    Some(EmbedManifest {
        libkrun: Some(libkrun.clone()),
        kernel,
        rootfs,
        firmware,
        runtime_support: collect_runtime_support(&lib_dir, &libkrun),
    })
}

fn collect_runtime_support(lib_dir: &Path, libkrun: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let Ok(entries) = fs::read_dir(lib_dir) else {
        return files;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() || path == libkrun {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        files.push(path);
    }
    files.sort();
    files
}

fn render_required_asset(name: &str, path: &Path, out_dir: &Path) -> String {
    println!("cargo:rerun-if-changed={}", path.display());
    format!(
        "pub static {name}: Option<EmbeddedAsset> = Some({asset});\n",
        asset = render_embedded_asset(path, out_dir),
    )
}

fn render_optional_asset(name: &str, path: Option<&Path>, out_dir: &Path) -> String {
    match path {
        Some(path) => render_required_asset(name, path, out_dir),
        None => format!("pub static {name}: Option<EmbeddedAsset> = None;\n"),
    }
}

fn render_asset_entry(path: &Path, out_dir: &Path) -> String {
    format!("    {},\n", render_embedded_asset(path, out_dir))
}

fn render_embedded_asset(path: &Path, out_dir: &Path) -> String {
    let (asset_path, compression) = write_embedded_asset(path, out_dir);
    format!(
        "EmbeddedAsset {{ file_name: {file_name:?}, bytes: include_bytes!(r#\"{asset_path}\"#), compression: Compression::{compression}, mode: {mode}, }}",
        file_name = file_name(path),
        asset_path = asset_path.display(),
        compression = compression.variant_name(),
        mode = asset_mode(path),
    )
}

fn write_embedded_asset(path: &Path, out_dir: &Path) -> (PathBuf, CompressionMode) {
    let asset_dir = out_dir.join("embedded-assets");
    fs::create_dir_all(&asset_dir).expect("create embedded asset dir");
    let source = fs::read(path).expect("read embedded asset");
    let compressed = encode_all(Cursor::new(&source), 3).expect("compress embedded asset");
    if compressed.len() >= source.len() {
        return (path.to_path_buf(), CompressionMode::None);
    }
    let output_name = compressed_file_name(path);
    let output_path = asset_dir.join(output_name);
    fs::write(&output_path, compressed).expect("write compressed embedded asset");
    (output_path, CompressionMode::Zstd)
}

fn compressed_file_name(path: &Path) -> String {
    let original = file_name(path);
    format!("{original}.zst")
}

impl CompressionMode {
    fn variant_name(self) -> &'static str {
        match self {
            Self::None => "None",
            Self::Zstd => "Zstd",
        }
    }
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("artifact.bin")
        .to_string()
}

fn resolve_workspace_root(manifest_dir: &Path) -> PathBuf {
    for candidate in manifest_dir.ancestors() {
        let cargo_toml = candidate.join("Cargo.toml");
        let Ok(contents) = fs::read_to_string(&cargo_toml) else {
            continue;
        };
        if contents.contains("[workspace]") {
            return candidate.to_path_buf();
        }
    }
    manifest_dir.to_path_buf()
}
